-- Documentation
-- http://www.postgresql.org/docs/9.5/static/functions-datetime.html

-- current time/date
SELECT CURRENT_TIMESTAMP;
SELECT CURRENT_DATE;
SELECT CURRENT_TIME;
SELECT LOCALTIMESTAMP;
SELECT LOCALTIME;

CREATE TABLE t (
    a TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    b TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    c INTEGER
);
INSERT INTO t (c) VALUES (1);
INSERT INTO t (c) VALUES (2);
INSERT INTO t (c) VALUES (3);
SELECT * FROM t;
DROP TABLE IF EXISTS t;

-- AT TIME ZONE
CREATE TABLE t (
    a TIMESTAMP WITH TIME ZONE,
    b TIMESTAMP
);
INSERT INTO t VALUES ( CURRENT_TIMESTAMP, LOCALTIMESTAMP );
SELECT * FROM t;
SELECT a AT TIME ZONE 'EDT' AS a, b AT TIME ZONE 'EDT' AS b FROM t;
SELECT a AT TIME ZONE 'UTC' AS a, b AT TIME ZONE 'UTC' AS b FROM t;
SELECT a AT TIME ZONE INTERVAL '+3:30' AS a, b AT TIME ZONE INTERVAL '+03:30' AS b FROM t;
DROP TABLE IF EXISTS t;

-- date and time arithmetic

SELECT DATE '2015-10-28' - DATE '2015-10-08';
SELECT DATE '2015-10-28' - INTERVAL '6 days';
SELECT TIMESTAMP '2015-10-25 15:35:00' - INTERVAL '6 days 3 hours 35 minutes';

-- EXTRACT
SELECT EXTRACT(HOUR FROM TIMESTAMP '2015-10-28 15:01:25');
SELECT EXTRACT(MONTH FROM INTERVAL '3 years 2 months 1 hour 15 minutes');
